export const workflowRecipes = [
  { slug: 'clean-encode-json', name: 'Clean and encode JSON', category: 'JSON & Data', description: 'Format JSON, sort every object key, then encode the result as Base64.', details: 'Useful when an API, environment variable, or configuration field expects deterministic Base64-encoded JSON.', transforms: ['json-format','json-sort','base64-encode'], exampleInput: '{"version":2,"name":"PlainUtils","local":true}', exampleOutput: 'ewogICJsb2NhbCI6IHRydWUsCiAgIm5hbWUiOiAiUGxhaW5VdGlscyIsCiAgInZlcnNpb24iOiAyCn0=', tags: ['json','base64','configuration'], featured: true },
  { slug: 'inspect-jwt-payload', name: 'Inspect a JWT payload', category: 'Developer Debugging', description: 'Decode a JWT payload and format its claims as readable JSON.', details: 'This recipe helps inspect claims during development. Decoding does not verify the token signature or prove authenticity.', transforms: ['jwt-payload','json-format'], exampleInput: 'eyJhbGciOiJub25lIn0.eyJzdWIiOiIxMjMiLCJuYW1lIjoiQWRhIn0.', exampleOutput: '{\n  "sub": "123",\n  "name": "Ada"\n}', tags: ['jwt','json','debugging'], featured: true },
  { slug: 'yaml-to-sorted-json', name: 'YAML to sorted JSON', category: 'JSON & Data', description: 'Convert a YAML document to readable JSON and sort its object keys.', details: 'Ideal for comparing configuration files or producing stable JSON output from human-authored YAML.', transforms: ['yaml-json','json-sort'], exampleInput: 'version: 2\nname: PlainUtils\nfeatures:\n  - local\n  - fast', exampleOutput: '{\n  "features": [\n    "local",\n    "fast"\n  ],\n  "name": "PlainUtils",\n  "version": 2\n}', tags: ['yaml','json','configuration'], featured: true },
  { slug: 'decode-url-json', name: 'Decode and format URL JSON', category: 'Encoding', description: 'URL-decode a value and immediately format the resulting JSON.', details: 'Useful for inspecting encoded query parameters, callback payloads, and JSON copied from URLs.', transforms: ['url-decode','json-format'], exampleInput: '%7B%22name%22%3A%22Ada%22%2C%22active%22%3Atrue%7D', exampleOutput: '{\n  "name": "Ada",\n  "active": true\n}', tags: ['url','json','decode'], isNew: true },
  { slug: 'clean-sort-lines', name: 'Clean and sort text lines', category: 'Text Cleanup', description: 'Trim text, remove repeated lines, and sort the remainder.', details: 'Good for tidying lists of domains, identifiers, email addresses, package names, or other line-oriented data.', transforms: ['trim','dedupe-lines','sort-lines'], exampleInput: 'pear\napple\npear\nbanana', exampleOutput: 'apple\nbanana\npear', tags: ['text','deduplicate','sort'], featured: true },
  { slug: 'decode-base64-json', name: 'Decode Base64 JSON', category: 'Encoding', description: 'Decode Base64 text and format the result as JSON.', details: 'Use this for Base64-encoded configuration blobs and development payloads that contain UTF-8 JSON.', transforms: ['base64-decode','json-format'], exampleInput: 'eyJuYW1lIjoiUGxhaW5VdGlscyIsImxvY2FsIjp0cnVlfQ==', exampleOutput: '{\n  "name": "PlainUtils",\n  "local": true\n}', tags: ['base64','json','decode'], isNew: true },
  { slug: 'normalize-url-slug', name: 'Normalize text for a URL', category: 'Text Cleanup', description: 'Trim text, lowercase it, then safely URL-encode it.', details: 'A compact recipe for normalizing labels and free-form values before placing them in a URL component.', transforms: ['trim','lowercase','url-encode'], exampleInput: '  Plain Utils & Tools  ', exampleOutput: 'plain%20utils%20%26%20tools', tags: ['text','url','normalize'] },
  { slug: 'json-to-yaml-config', name: 'JSON to YAML configuration', category: 'JSON & Data', description: 'Sort JSON object keys and convert the document to YAML.', details: 'Useful when moving machine-generated JSON configuration into a more readable YAML-based project.', transforms: ['json-sort','json-yaml'], exampleInput: '{"version":2,"name":"PlainUtils","enabled":true}', exampleOutput: 'enabled: true\nname: PlainUtils\nversion: 2\n', tags: ['json','yaml','configuration'], isNew: true },
];

export const recipeCategories = [...new Set(workflowRecipes.map((recipe) => recipe.category))];
export const recipeBySlug = Object.fromEntries(workflowRecipes.map((recipe) => [recipe.slug, recipe]));
