import { useEffect, useState } from 'react';
import Link from 'next/link';
import Layout from '../components/Layout';
import ToolCard from '../components/ToolCard';
import { toolByHref, tools } from '../lib/tools';
import { ArrowRight, Command, ShieldCheck, Sparkles, Workflow, Zap } from 'lucide-react';

export default function Home() {
  const [recent, setRecent] = useState([]);
  useEffect(() => setRecent(JSON.parse(localStorage.getItem('plainutils:recent') || '[]').map((href) => toolByHref[href]).filter(Boolean)), []);
  return <Layout title="PlainUtils">
    <section className="hero-stage text-center max-w-5xl mx-auto py-12 sm:py-20"><div className="hero-orb hero-orb-one" aria-hidden="true"/><div className="hero-orb hero-orb-two" aria-hidden="true"/><p className="hero-pill"><Sparkles /> Tiny tools. Surprisingly mighty.</p><h1 className="text-5xl sm:text-7xl font-black tracking-tight mt-6 mb-6"><span className="animated-gradient">Useful tools,</span><br/>without the nonsense.</h1><p className="text-lg sm:text-xl leading-8 text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">Fast browser utilities for developers and everyday work. No signup, no clutter, and your data usually never leaves your device.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/tools" className="btn !px-6 !py-3">Explore {tools.length} tools <ArrowRight /></Link><button className="btn-secondary !px-5 !py-3" onClick={() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 'k', metaKey: true }))}><Command />Quick search <kbd>⌘K</kbd></button></div><div className="mt-9 flex flex-wrap justify-center gap-x-7 gap-y-2 text-sm text-gray-500 dark:text-gray-400"><span className="hero-proof"><Zap/>Instant results</span><span className="hero-proof"><ShieldCheck/>Local-first privacy</span><span className="hero-proof"><Sparkles/>Free to use</span></div></section>
    {recent.length > 0 && <section className="mb-12"><h2 className="text-2xl font-bold mb-4">Recently used</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{recent.map((tool) => <ToolCard key={tool.href} tool={tool} />)}</div></section>}
    <section className="workflow-banner mb-12 overflow-hidden rounded-2xl text-white p-6 sm:p-8"><div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10"><div className="flex items-start gap-4"><span className="p-3 rounded-xl bg-white/15 ring-1 ring-white/20"><Workflow className="w-7 h-7"/></span><div><p className="text-sm font-semibold text-cyan-100 uppercase tracking-wide">PlainUtils Workflows</p><h2 className="text-2xl sm:text-3xl font-bold mt-1">Start with a recipe. Make it yours.</h2><p className="mt-2 text-blue-100 max-w-2xl">Chain transformations together without sending your content to a server.</p></div></div><div className="flex flex-wrap gap-2 shrink-0"><Link href="/workflows" className="inline-flex items-center justify-center gap-2 bg-white text-blue-700 px-5 py-3 rounded-lg font-semibold hover:bg-blue-50 focus:outline-none focus:ring-2 focus:ring-white">Browse recipes <ArrowRight className="w-4 h-4"/></Link><Link href="/workspace" className="inline-flex items-center justify-center px-5 py-3 rounded-lg font-semibold border border-white/40 hover:bg-white/10">Build your own</Link></div></div></section>
    <section><div className="flex justify-between items-end mb-5"><div><h2 className="text-2xl font-bold">Popular utilities</h2><p className="text-gray-600 dark:text-gray-400 mt-1">Start with the essentials.</p></div><Link href="/tools" className="text-blue-600 dark:text-blue-400 font-medium">View all {tools.length} →</Link></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{tools.slice(0, 9).map((tool) => <ToolCard key={tool.href} tool={tool} />)}</div></section>
    <section className="idea-card mt-14 text-center"><span className="text-3xl" aria-hidden="true">💡</span><h2 className="text-2xl font-bold mt-2">Got a useful little idea?</h2><p className="mt-2 text-gray-600 dark:text-gray-400">Tell us what would save you time. The best utilities often start tiny.</p><a href="mailto:plainutils@pingryte.com" className="btn mt-5">Suggest a tool</a></section>
  </Layout>;
}
