import { useEffect, useMemo, useRef, useState } from 'react';
import { BookMarked, Check, Clipboard, Download, ExternalLink, FileUp, Pin, Search, Trash2, Upload, X } from 'lucide-react';
import { useRouter } from 'next/router';
import Layout from '../components/Layout';
import InfoPageHero from '../components/InfoPageHero';
import { downloadText } from '../lib/tool-utils';
import { MAX_SNIPPETS, RETENTION_KEY, RESTORE_KEY, SNIPPETS_KEY, cleanSnippets, parseSnippetBackup, readSnippets } from '../lib/snippets';

export default function Library() {
  const [snippets, setSnippets] = useState([]); const [query, setQuery] = useState(''); const [tool, setTool] = useState('All'); const [selected, setSelected] = useState(null); const [notice, setNotice] = useState(''); const [retention, setRetention] = useState('never'); const fileRef = useRef(null); const router = useRouter();
  useEffect(() => { setSnippets(readSnippets(localStorage)); setRetention(localStorage.getItem(RETENTION_KEY) || 'never'); }, []);
  const persist = (next) => { const cleaned = cleanSnippets(next); setSnippets(cleaned); localStorage.setItem(SNIPPETS_KEY, JSON.stringify(cleaned)); };
  const notify = (value) => { setNotice(value); window.setTimeout(() => setNotice(''), 1800); };
  const tools = [...new Set(snippets.map((item) => item.toolTitle).filter(Boolean))].sort();
  const filtered = useMemo(() => snippets.filter((item) => (tool === 'All' || item.toolTitle === tool) && `${item.title} ${item.value} ${item.toolTitle}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt - a.updatedAt), [snippets, query, tool]);
  const update = (id, change) => persist(snippets.map((item) => item.id === id ? { ...item, ...change, updatedAt: Date.now() } : item));
  const remove = (id) => { persist(snippets.filter((item) => item.id !== id)); if (selected?.id === id) setSelected(null); };
  const copy = async (value) => { await navigator.clipboard.writeText(value); notify('Copied to clipboard'); };
  const restore = (item) => { localStorage.setItem(RESTORE_KEY, JSON.stringify({ toolHref: item.toolHref, value: item.value })); router.push(item.toolHref); };
  const exportAll = () => downloadText(JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), snippets }, null, 2), 'plainutils-library.json', 'application/json');
  const importFile = (file) => { const reader = new FileReader(); reader.onload = () => { try { const imported = parseSnippetBackup(String(reader.result)); persist([...imported, ...snippets].slice(0, MAX_SNIPPETS)); notify(`Imported ${imported.length} snippets`); } catch (error) { notify(error.message); } }; reader.readAsText(file); };
  const changeRetention = (value) => { setRetention(value); localStorage.setItem(RETENTION_KEY, value); notify('Default retention updated'); };

  return <Layout title="Snippet Library" hidePageHeader description="Save, search, pin, restore, and back up reusable PlainUtils snippets locally."><InfoPageHero eyebrow="Your local shelf" title="Keep the useful bits." description="Save outputs you will need again, pin the important ones, and restore them without creating an account. Your Library lives entirely in this browser." icon={BookMarked} tone="violet"><span className="info-chip"><BookMarked />{snippets.length} saved</span><span className="info-chip"><Pin />{snippets.filter((item) => item.pinned).length} pinned</span><span className="info-chip"><DatabaseIcon />Local only</span></InfoPageHero>
    <section className="library-toolbar mt-8"><label className="relative flex-1"><span className="sr-only">Search snippets</span><Search className="absolute w-5 h-5 left-3 top-3 text-gray-400"/><input className="textarea-base !py-2.5 !pl-10" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search names, content, or tools…"/></label><label><span className="sr-only">Filter by tool</span><select className="textarea-base !p-2.5" value={tool} onChange={(event) => setTool(event.target.value)}><option>All</option>{tools.map((name) => <option key={name}>{name}</option>)}</select></label><button className="btn-secondary" onClick={exportAll} disabled={!snippets.length}><Download />Export</button><button className="btn-secondary" onClick={() => fileRef.current?.click()}><Upload />Import</button><input ref={fileRef} className="sr-only" type="file" accept="application/json,.json" aria-label="Import snippet backup" onChange={(event) => event.target.files[0] && importFile(event.target.files[0])}/></section>
    <div className="flex flex-wrap justify-between items-center gap-3 mt-4"><p className="text-sm text-gray-500">Showing {filtered.length} of {snippets.length} · Up to {MAX_SNIPPETS} snippets</p><label className="flex items-center gap-2 text-sm"><span>New snippets expire</span><select className="textarea-base !p-1.5 !w-auto" value={retention} onChange={(event) => changeRetention(event.target.value)}><option value="never">Never</option><option value="7">After 7 days</option><option value="30">After 30 days</option><option value="90">After 90 days</option></select></label></div>
    {notice && <p className="success-message flex items-center gap-1" role="status"><Check className="w-4 h-4"/>{notice}</p>}
    {filtered.length ? <section className="grid md:grid-cols-2 xl:grid-cols-3 gap-4 mt-6" aria-label="Saved snippets">{filtered.map((item) => <article className="snippet-card" key={item.id}><div className="flex justify-between gap-3"><div className="min-w-0"><span className="text-xs font-bold uppercase tracking-wide text-violet-600 dark:text-violet-300">{item.toolTitle || 'PlainUtils'}</span><input aria-label={`Rename ${item.title}`} className="block w-full bg-transparent font-bold text-lg mt-1 outline-none focus:ring-2 focus:ring-blue-500 rounded" value={item.title} onChange={(event) => update(item.id, { title: event.target.value.slice(0, 100) })}/></div><button className={`icon-button ${item.pinned ? 'text-amber-500' : 'text-gray-400'}`} aria-label={`${item.pinned ? 'Unpin' : 'Pin'} ${item.title}`} aria-pressed={item.pinned} onClick={() => update(item.id, { pinned: !item.pinned })}><Pin className={item.pinned ? 'fill-amber-400' : ''}/></button></div><button className="snippet-preview" onClick={() => setSelected(item)} aria-label={`Preview ${item.title}`}>{item.value.slice(0, 240)}{item.value.length > 240 ? '…' : ''}</button><p className="text-xs text-gray-500 mt-3">Saved {new Date(item.createdAt).toLocaleDateString()}{item.expiresAt ? ` · Expires ${new Date(item.expiresAt).toLocaleDateString()}` : ''}</p><div className="flex flex-wrap gap-1 mt-3"><button className="btn-secondary !py-1.5" onClick={() => copy(item.value)}><Clipboard />Copy</button>{item.toolHref && <button className="btn-secondary !py-1.5" onClick={() => restore(item)}><ExternalLink />Restore</button>}<button className="icon-button ml-auto text-rose-600" aria-label={`Delete ${item.title}`} onClick={() => remove(item.id)}><Trash2 /></button></div></article>)}</section> : <section className="empty-state mt-6"><BookMarked className="w-10 h-10 mx-auto text-violet-500"/><h2 className="text-xl font-bold mt-3">{snippets.length ? 'No snippets match' : 'Your shelf is ready'}</h2><p className="text-gray-500 mt-2">{snippets.length ? 'Try a different search or tool filter.' : 'Use “Save” in a tool’s action bar to add your first reusable result.'}</p></section>}
    {snippets.length > 0 && <div className="flex justify-end mt-8"><button className="btn-secondary text-rose-600" onClick={() => { if (window.confirm('Delete every saved snippet from this browser?')) { persist([]); setSelected(null); } }}><Trash2 />Clear Library</button></div>}
    {selected && <div className="dialog-backdrop" onMouseDown={() => setSelected(null)}><section className="snippet-dialog" role="dialog" aria-modal="true" aria-labelledby="snippet-preview-title" onMouseDown={(event) => event.stopPropagation()}><div className="flex justify-between gap-3"><div><p className="section-kicker">{selected.toolTitle || 'Saved snippet'}</p><h2 id="snippet-preview-title" className="text-xl font-bold mt-1">{selected.title}</h2></div><button className="icon-button" aria-label="Close snippet preview" onClick={() => setSelected(null)}><X /></button></div><pre className="mt-5 max-h-[55vh] overflow-auto whitespace-pre-wrap break-words rounded-xl bg-gray-950 text-gray-100 p-4 text-sm" tabIndex="0">{selected.value}</pre><div className="flex justify-end gap-2 mt-4"><button className="btn-secondary" onClick={() => copy(selected.value)}><Clipboard />Copy</button>{selected.toolHref && <button className="btn" onClick={() => restore(selected)}><ExternalLink />Restore in tool</button>}</div></section></div>}
  </Layout>;
}

function DatabaseIcon() { return <FileUp />; }
