import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ChevronDown, ChevronUp, Copy, Download, GripVertical, Link2, Play, Plus, Save, ShieldCheck, Trash2, Upload, X } from 'lucide-react';
import Layout from '../components/Layout'; import FileDrop from '../components/FileDrop'; import ToolActions from '../components/ToolActions';
import Link from 'next/link';
import { applyTransform, pipelineTransforms } from '../lib/transforms'; import { downloadText } from '../lib/tool-utils';
import { createSharePayload, decodeSharedWorkflow, encodeSharedWorkflow, MAX_SHARE_URL_LENGTH } from '../lib/workflow-share';
import { workflowRecipes } from '../lib/workflow-recipes';

const newStep = (transform = 'json-format') => ({ id: crypto.randomUUID(), transform, enabled: true });
const presets = workflowRecipes.filter((recipe) => recipe.featured).slice(0, 4).map((recipe) => ({ ...recipe, input: recipe.exampleInput }));

export default function Workspace() {
  const importRef = useRef(null); const [input,setInput]=useState(''); const [name,setName]=useState('Untitled workflow'); const [workflowId,setWorkflowId]=useState(null); const [steps,setSteps]=useState([]); const [results,setResults]=useState([]); const [saved,setSaved]=useState([]); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [sharedNotice,setSharedNotice]=useState(false); const [running,setRunning]=useState(false); const [dragged,setDragged]=useState(null);
  useEffect(()=>{let loadedShared=false;const encoded=new URLSearchParams(window.location.hash.slice(1)).get('workflow');if(encoded){try{const shared=decodeSharedWorkflow(encoded,new Set(pipelineTransforms.map(([id])=>id)));setName(shared.name);setSteps(shared.steps.map(step=>({...step,id:crypto.randomUUID()})));setWorkflowId(null);setSharedNotice(true);loadedShared=true}catch(caught){setError(caught.message)}}const incoming=localStorage.getItem('plainutils:pipeline-input');if(incoming){setInput(incoming);localStorage.removeItem('plainutils:pipeline-input')}if(!loadedShared){const storedSteps=localStorage.getItem('plainutils:pipeline-steps');if(storedSteps)try{setSteps(JSON.parse(storedSteps))}catch{}}const storedWorkflows=localStorage.getItem('plainutils:workflows');if(storedWorkflows)try{setSaved(JSON.parse(storedWorkflows))}catch{}},[]);
  useEffect(()=>{if(steps.length)localStorage.setItem('plainutils:pipeline-steps',JSON.stringify(steps));else localStorage.removeItem('plainutils:pipeline-steps')},[steps]);
  const flash=(message)=>{setNotice(message);window.setTimeout(()=>setNotice(''),2200)};
  const run=async()=>{setRunning(true);setError('');const next=[];let value=input;try{for(let index=0;index<steps.length;index+=1){if(steps[index].enabled!==false)value=await applyTransform(steps[index].transform,value);next[index]=value}setResults(next)}catch(caught){setError(`Step ${next.length+1}: ${caught.message}`);setResults(next)}finally{setRunning(false)}};
  const save=()=>{const cleanName=name.trim()||'Untitled workflow';const record={id:workflowId||crypto.randomUUID(),name:cleanName,steps,updatedAt:new Date().toISOString()};const next=[record,...saved.filter(item=>item.id!==record.id)];setSaved(next);setName(cleanName);setWorkflowId(record.id);localStorage.setItem('plainutils:workflows',JSON.stringify(next));flash('Workflow saved on this device')};
  const load=(workflow)=>{setWorkflowId(workflow.id);setName(workflow.name);setSteps(workflow.steps.map(step=>({...step,id:crypto.randomUUID()})));setResults([]);setError('');flash(`Loaded ${workflow.name}`)};
  const removeSaved=(id)=>{const next=saved.filter(item=>item.id!==id);setSaved(next);localStorage.setItem('plainutils:workflows',JSON.stringify(next));if(workflowId===id)setWorkflowId(null)};
  const loadPreset=(preset)=>{setWorkflowId(null);setName(preset.name);setInput(preset.input);setSteps(preset.transforms.map(newStep));setResults([]);setError('');flash('Starter workflow loaded')};
  const duplicate=(index)=>setSteps([...steps.slice(0,index+1),{...steps[index],id:crypto.randomUUID()},...steps.slice(index+1)]);
  const move=(from,to)=>{if(to<0||to>=steps.length)return;const next=[...steps];const[item]=next.splice(from,1);next.splice(to,0,item);setSteps(next);setResults([])};
  const drop=(targetId)=>{const from=steps.findIndex(step=>step.id===dragged);const to=steps.findIndex(step=>step.id===targetId);if(from>=0&&to>=0)move(from,to);setDragged(null)};
  const exportWorkflow=()=>downloadText(JSON.stringify({version:1,name,steps:steps.map(({transform,enabled})=>({transform,enabled}))},null,2),`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'workflow'}.plainutils.json`,'application/json');
  const shareWorkflow=async()=>{try{const encoded=encodeSharedWorkflow(createSharePayload(name,steps));const url=`${window.location.origin}${window.location.pathname}#workflow=${encoded}`;if(url.length>MAX_SHARE_URL_LENGTH)throw new Error('This workflow is too large to share as a link. Export it as a file instead.');await navigator.clipboard.writeText(url);window.history.replaceState(null,'',`#workflow=${encoded}`);flash('Private workflow link copied')}catch(caught){setError(caught.message||'Unable to copy the workflow link.')}};
  const importWorkflow=(file)=>{const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.version!==1||!Array.isArray(data.steps)||data.steps.some(step=>!pipelineTransforms.some(([id])=>id===step.transform)))throw new Error('Unsupported or invalid workflow file.');setWorkflowId(null);setName(data.name||'Imported workflow');setSteps(data.steps.map(step=>newStep(step.transform)).map((step,index)=>({...step,enabled:data.steps[index].enabled!==false})));setResults([]);setError('');flash('Workflow imported')}catch(caught){setError(caught.message)}};reader.readAsText(file)};
  const output=results.at(-1)??input;

  return <Layout title="Pipeline Workspace" metaTitle="Local Tool Pipeline Workspace | PlainUtils" description="Create, save, import, and reuse local workflows that chain PlainUtils transformations.">
    {sharedNotice&&<div className="mb-6 p-4 rounded-lg border border-blue-200 bg-blue-50 dark:border-blue-800 dark:bg-blue-950 flex items-start justify-between gap-4" role="status"><div><strong>Shared workflow loaded</strong><p className="text-sm text-gray-600 dark:text-gray-300 mt-1">Only its name and transformation steps came from the link. Review the steps, add your own input, then run or save it.</p></div><button className="icon-button" aria-label="Dismiss shared workflow notice" onClick={()=>setSharedNotice(false)}><X/></button></div>}
    <section className="panel mb-6" aria-labelledby="pipeline-guide-title"><div className="flex flex-col md:flex-row md:items-start justify-between gap-5"><div><h2 id="pipeline-guide-title" className="text-xl font-bold">How pipelines work</h2><p className="mt-2 text-gray-600 dark:text-gray-300 max-w-3xl">Your input passes through each enabled transformation in order. Preview every intermediate result, then save the workflow or copy a private share link.</p></div><button className="btn-secondary shrink-0" onClick={()=>loadPreset(presets[0])}>Load example pipeline</button></div><ol className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-5">{[['1','Add input','Type, paste, drop a file, or send output from another tool.'],['2','Build steps','Add, reorder, duplicate, or temporarily disable transformations.'],['3','Run and inspect','Preview the output produced after every enabled step.'],['4','Save or share','Save locally, export a file, or copy a link containing steps only.']].map(([number,title,text])=><li key={number} className="flex gap-3"><span className="w-7 h-7 shrink-0 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold text-sm">{number}</span><span><strong className="block">{title}</strong><span className="text-sm text-gray-600 dark:text-gray-400">{text}</span></span></li>)}</ol><div className="mt-5 pt-4 border-t border-gray-200 dark:border-gray-700 flex items-start gap-2 text-sm text-gray-600 dark:text-gray-300"><ShieldCheck className="w-5 h-5 shrink-0 text-green-600"/><p><strong>Private by design:</strong> processing remains in your browser. Saved and shared workflow definitions contain transformation names only; input and results are never included.</p></div></section>

    <section className="mb-7" aria-labelledby="starter-title"><div className="flex justify-between items-end mb-3"><h2 id="starter-title" className="text-xl font-bold">Starter workflows</h2><Link href="/workflows" className="text-blue-600 dark:text-blue-400 font-medium">View all recipes →</Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{presets.map(preset=><button key={preset.name} className="tool-card text-left" onClick={()=>loadPreset(preset)}><strong className="block">{preset.name}</strong><span className="block text-sm text-gray-500 mt-1">{preset.description}</span></button>)}</div></section>

    <section className="panel mb-6" aria-labelledby="manage-title"><div className="flex flex-col lg:flex-row lg:items-end gap-3"><div className="flex-1"><label className="field-label" htmlFor="workflow-name">Workflow name</label><input id="workflow-name" className="textarea-base !p-2.5" value={name} onChange={event=>setName(event.target.value)}/></div><div className="flex flex-wrap gap-2"><button className="btn" onClick={save} disabled={!steps.length}><Save/> Save</button><button className="btn-secondary" onClick={shareWorkflow} disabled={!steps.length}><Link2/> Copy share link</button><button className="btn-secondary" onClick={exportWorkflow} disabled={!steps.length}><Download/> Export</button><button className="btn-secondary" onClick={()=>importRef.current?.click()}><Upload/> Import</button><input ref={importRef} type="file" accept=".json,.plainutils.json" aria-label="Import workflow file" className="sr-only" onChange={event=>importWorkflow(event.target.files[0])}/></div></div>{notice&&<p className="success-message" aria-live="polite">{notice}</p>}{saved.length>0&&<div className="mt-4 pt-4 border-t dark:border-gray-700"><h3 id="manage-title" className="font-bold mb-2">Saved on this device</h3><div className="flex flex-wrap gap-2">{saved.map(workflow=><span key={workflow.id} className="inline-flex items-center border dark:border-gray-700 rounded-md"><button className="px-3 py-2 hover:bg-gray-100 dark:hover:bg-gray-800" onClick={()=>load(workflow)}>{workflow.name}</button><button className="icon-button rounded-l-none" onClick={()=>removeSaved(workflow.id)} aria-label={`Delete saved workflow ${workflow.name}`}><Trash2/></button></span>)}</div></div>}</section>

    <div className="grid lg:grid-cols-[1fr_26rem] gap-6"><section><FileDrop accept=".txt,.json,.yaml,.yml,.csv,.md,.html,.css,.js" onFile={({text})=>setInput(text)}/><label className="field-label mt-4" htmlFor="pipeline-input">Pipeline input</label><textarea id="pipeline-input" className="textarea-base h-52 font-mono" value={input} onChange={event=>setInput(event.target.value)}/><ToolActions value={output} onClear={()=>{setInput('');setResults([])}} filename="pipeline-output.txt"/><label className="field-label mt-5" htmlFor="pipeline-output">Final output</label><textarea id="pipeline-output" className="textarea-base h-64 font-mono" value={output} readOnly/></section>
      <aside><div className="flex justify-between items-center mb-3"><h2 className="text-xl font-bold">Transformation steps</h2><button className="btn-secondary" onClick={()=>setSteps([...steps,newStep()])}><Plus/> Add</button></div>{!steps.length&&<p className="panel text-sm text-gray-500">No steps yet. Add a transformation or choose a starter workflow.</p>}<div className="space-y-2">{steps.map((step,index)=><div key={step.id} draggable onDragStart={()=>setDragged(step.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>drop(step.id)} className={step.enabled===false?'opacity-60':''}><div className="panel !p-3"><div className="flex gap-2 items-center"><GripVertical className="w-4 h-4 text-gray-400 cursor-grab" aria-hidden="true"/><span className="font-bold">{index+1}</span><select aria-label={`Transformation ${index+1}`} className="textarea-base !p-2" value={step.transform} onChange={event=>setSteps(steps.map(item=>item.id===step.id?{...item,transform:event.target.value}:item))}>{pipelineTransforms.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><div className="flex items-center justify-between mt-2"><label className="text-sm"><input type="checkbox" checked={step.enabled!==false} onChange={event=>setSteps(steps.map(item=>item.id===step.id?{...item,enabled:event.target.checked}:item))}/> Enabled</label><span className="flex"><button className="icon-button" onClick={()=>move(index,index-1)} disabled={index===0} aria-label={`Move step ${index+1} up`}><ChevronUp/></button><button className="icon-button" onClick={()=>move(index,index+1)} disabled={index===steps.length-1} aria-label={`Move step ${index+1} down`}><ChevronDown/></button><button className="icon-button" onClick={()=>duplicate(index)} aria-label={`Duplicate step ${index+1}`}><Copy/></button><button className="icon-button" onClick={()=>setSteps(steps.filter(item=>item.id!==step.id))} aria-label={`Remove step ${index+1}`}><Trash2/></button></span></div>{results[index]!==undefined&&<details className="mt-2"><summary className="text-sm text-blue-600 dark:text-blue-400 cursor-pointer">Preview step output</summary><pre className="mt-2 max-h-40 overflow-auto text-xs bg-gray-50 dark:bg-gray-950 p-2 rounded whitespace-pre-wrap break-all">{results[index]}</pre></details>}</div>{index<steps.length-1&&<ArrowDown className="w-4 h-4 mx-auto text-gray-400"/>}</div>)}</div><button className="btn w-full mt-4" onClick={run} disabled={running||!steps.length}><Play/>{running?'Running…':'Run pipeline'}</button>{error&&<p className="error-message" role="alert">{error}</p>}</aside>
    </div>
  </Layout>;
}
